### ISSUE TITLE
Default assistant as Xposed alternative

### ISSUE THREAD

**Issue by null-von-sushi** [KieronQuinn/ClassicPowerMenu#100]
Would it be possible to have the app simply become the default assistant, so that users can long-press the power button in order to invoke it? If I understand the current method relies on essentially highjacking the long-press of the power button, however since google made long pressing the power button show the default assistant, it should be possible to start ClassicPowerMenu that way, right?

My end goal is to get this running on Graphene OS (custom build with root), however the strict security of the OS unfortunately doesn't  allow for something like Xposed to run.

**Comment by UltraStudioLTD** [comment]
@KieronQuinn

Android settings provide string called **"power_button_long_press"** in **[Global Table]** part which overrides what happens during long press of power button depending on it's value:

1. **0** — "Do Nothing" (*long-pressing the power button does nothing*)
2. **1** — "Global Actions" (show the normal power menu*)
3. **2** — "Shut Off" (*power down the phone*)
4. **3** — "Shut Off No Confirm" (*power down the phone immediately*)
5. **4** — "Go To Voice Assist" (*launches the old **Assistant** UI with a top-down dialog and **"Search A Song"** button*)
6. **5** — "Assistant" (*launches the default **Assistant** service as defined in **"Default Apps"** under **Settings***)

It's very easy to edit it's value, especially with root or even **ADB**, so if we set value to **5** and then selected **ClassicPowerMenu** as **Default Assistant**, no power menu would pop-up, except **ClassicPowerMenu**'s. Only problem is that this requires **.ui.activities.PowerMenuActivity** to be defined as **Assistant** activity which should be just a few more lines in [**AndroidManifest.xml**](https://github.com/KieronQuinn/ClassicPowerMenu/blob/main/app/src/main/AndroidManifest.xml) and activity's source code. Unfortunately I don't have any knowledge of **Java/Kotlin** or APK building so I can't help. Can you please add necessary code?

As far as I know you only need to add this declaration before this [line](https://github.com/KieronQuinn/ClassicPowerMenu/blob/1de80e29a0e14fad4d618b4aa5303ea17cb1133f/app/src/main/AndroidManifest.xml#L38) in [AndroidManifest.xml](https://github.com/KieronQuinn/ClassicPowerMenu/blob/main/app/src/main/AndroidManifest.xml):
```xml
<action android:name="android.intent.action.ASSIST"/>
```
and then add necessary broadcast receiver in **PowerMenuActivity**'s source code

**Comment by KieronQuinn** [comment]
I added the action to 1.7. There's no UI to enable it, it doesn't do anything special with the settings, so you'll need to just enable it yourself:

- Set CPM as the assistant app
- Set the power button action to open assistant

Tested and this works on a P6P

**Comment by null-von-sushi** [comment]
Indeed works, thank you so much for adding it!

For anyone that reads this in the future and found the issue by searching: All that's necessary is `settings put global power_button_long_press 5` in order to change the default long-press power button behaviour, as there's no UI to switch it in Graphene OS.

(If anyone wants to use Google assistant, which requires to be the default assistant in order to work, they can try using something like tasker to make a shortcut to first switch the default assistant, run Google assistant, then switch it back again. But that's outside the scope of this issue.)

Thanks again for giving is this option 🙏
