### ISSUE TITLE
Crash on A14 Beta 3 Again

### ISSUE THREAD

**Issue by acwcanada** [KieronQuinn/ClassicPowerMenu#101]
v1.6.1 fixed the crashing on A14 Beta 1 and v1.6.2 is working with A14 Beta 2 and Beta 2.1, but now it crashing again with the new release of A14 Beta 3. Hope you can get it fixed soon.

**Comment by KieronQuinn** [comment]
Aware, fixing it now.

**Comment by KieronQuinn** [comment]
Fixed in 1.7
