### ISSUE TITLE
Way to trigger via tasker? 

### ISSUE THREAD

**Issue by e0xify** [KieronQuinn/ClassicPowerMenu#105]
Just saw the new update, but it seems that oneui does not Support changing the Assistant.

I found a way to remap the Button to tasker to open an App for me.

When i select classic Power Menu, the settings get opened, is there a way to trigger the correct view?

Thanks

**Comment by KieronQuinn** [comment]
Already possible:

System > Send Intent

Set the data as shown and the target to activity. That's all.

![image](https://github.com/KieronQuinn/ClassicPowerMenu/assets/3430869/1739be57-b642-4a81-9f60-a807665e0fb8)
