### ISSUE TITLE
Pixel 6 Pro - Home Device Controls do not work on latest June stock ROM

### ISSUE THREAD

**Issue by adrianmmiller** [KieronQuinn/ClassicPowerMenu#107]
Pixel 6 Pro - Home Device Controls do not work on latest June stock ROM

The minute i hit Home from the Device Controls choices (Macrodroid also appears), it fc's....

Just me?

**Comment by KieronQuinn** [comment]
#75

**Comment by rom4ster** [comment]
I would like to state that it might be possible that this may not be a duplicate I looked at your comment on the other post and I noticed that the exception was actually different. I can post more details but it seems that one of the layout inflators for the controls is not working correctly specifically where you expect a View group for something. I'm still investigating but I replayed the changes from the pr for the 1.7 release line by line and I saw that this happened after the updating of the Gradle dependencies and then fixing the CSM problems that arise from that. You are right that it probably does not have to do with the default assistant stuff by the looks of it.

**Comment by KieronQuinn** [comment]
If it's something View related, I'm not fixing it, sorry. Controls is an AOSP component that has moved on, it's not something I'll be maintaining. 

The Google Home app in particular is moving to embedded controls anyway, which this app won't support.

**Comment by rom4ster** [comment]
This app has gone from not adding features to losing features which, while disappointing, I can understand from a point of view of obviously you doing this for free and not having infinite time. 

I want to say though that this feature is technically in scope as smart home controls were a part of the android 11 menu which this app claims to be a replacement and improvement for. In fact device controls are part of the first line of the xda description. 

If we are going to be losing in scope features like this, it seems the primary concern of the app is the payment/loyalty cards and the custom power options. Could those be split out into modules that other projects could use. This would hyper focus the scope which would free up time to look into how google wallet works as we still dont have a full understanding of that. 

Also if you are no longer going to support these controls, removing them in an update would probably be better (though I am trying to fix this atm but I am not really good at android dev). 

Really the biggest "smart home" use cases are actually running tasker tasks. 

I know you are against added scope but I will throw this out there just in case. One option is to replace the smart home area with a recycler view or something that can allow you to launch an app. This would keep the tasker functionality (tasker can create apps for you) without going through and using the takser api, and does not seem ... too difficult to do from what I remember when i was (failing hardcore at) making launchers.

**Comment by rom4ster** [comment]
Ok I think I managed to fix it and TECHNICALLY its not a code issue but a xml file issue, ill fork and PR

**Comment by adrianmmiller** [comment]
fwiw, i rolled back to 1.6.2 and got all the controls back, but sacrificed swiping to change to a loyalty card

**Comment by adrianmmiller** [comment]
> Ok I think I managed to fix it and TECHNICALLY its not a code issue but a xml file issue, ill fork and PR
> 
> PR MADE
> 
> @adrianmmiller if you want you can try my build thats in the linked pr

thanks ill give it a go

**Comment by rom4ster** [comment]
> > Ok I think I managed to fix it and TECHNICALLY its not a code issue but a xml file issue, ill fork and PR
> > PR MADE
> > @adrianmmiller if you want you can try my build thats in the linked pr
> 
> thanks ill give id a go, if i knew how to do that :)

I made a release 4 u, just use the apk file https://github.com/rom4ster/Rom4PowerMenu/releases/tag/v0.1

**Comment by adrianmmiller** [comment]
> > > Ok I think I managed to fix it and TECHNICALLY its not a code issue but a xml file issue, ill fork and PR
> > > PR MADE
> > > @adrianmmiller if you want you can try my build thats in the linked pr
> > 
> > 
> > thanks ill give id a go, if i knew how to do that :)
> 
> I made a release 4 u, just use the apk file https://github.com/rom4ster/Rom4PowerMenu/releases/tag/v0.1 make sure you uninstall your current version first

Working fine thanks, controls are back

Loyalty cards still nto working, i suspect it may be a wallet related bug

**Comment by KieronQuinn** [comment]
> This app has gone from not adding features to losing features which, while disappointing, I can understand from a point of view of obviously you doing this for free and not having infinite time.
> 
> I want to say though that this feature is technically in scope as smart home controls were a part of the android 11 menu which this app claims to be a replacement and improvement for. In fact device controls are part of the first line of the xda description.
> 
> If we are going to be losing in scope features like this, it seems the primary concern of the app is the payment/loyalty cards and the custom power options. Could those be split out into modules that other projects could use. This would hyper focus the scope which would free up time to look into how google wallet works as we still dont have a full understanding of that.
> 
> Also if you are no longer going to support these controls, removing them in an update would probably be better (though I am trying to fix this atm but I am not really good at android dev).
> 
> Really the biggest "smart home" use cases are actually running tasker tasks.
> 
> I know you are against added scope but I will throw this out there just in case. One option is to replace the smart home area with a recycler view or something that can allow you to launch an app. This would keep the tasker functionality (tasker can create apps for you) without going through and using the takser api, and does not seem ... too difficult to do from what I remember when i was (failing hardcore at) making launchers.

The point of this app was to return controls to an easy location - technically, it was actually resolved by the OS before the app was even released (Google added them to the lock screen instead). 

Since it's been released, they've also added the ability to use controls while locked, and are adding loyalty cards to the Quick Access Wallet. I don't know whether this app put pressure on them to add those features to AOSP, but it may well have done. There's going to be little left of this app that's beneficial for devices running 14, other than more power menu options - which is a saturated market with many options of other apps. 

Controls are already migrating towards the new API, and supporting that would be difficult to impossible (depending on permissions), so I already knew this app would be discontinued *soon*, it's a question of when not if. It's been on life support mode for a while. In addition, the Controls module of the app was not created by me, it's from AOSP, and they were moved into a new area with a whole new UI in 12, so it's not as simple as just pulling a new commit.

You're welcome to fork and continue working on it of course, but adding features and fixing bugs introduced by newer OS versions in the modules I didn't even write, for me is simply not worth the time vs other apps which are more popular and have more benefit on newer devices. The app will also continue to work on older devices, since they won't be impacted by OS changes.

Discontinuing an app I've made is rare. But you have to remember, I do this for free, and there's simply not enough hours in a day to continue working on something like this forever.

I will merge any PRs which fix the bugs though, up until the point of full discontinuation.

**Comment by rom4ster** [comment]
Wait you are going to discontinue the WHOLE app? The loyalty cards are not served by google at all (and arguably the most important feature) 

I 100% understand your time thing though, I barely have enough time to deal with just using the apps I use and you have a lot of apps. Just FYI though, this app alone for me is reason enough to root your phone so just wanted you to know that its made a real positive impact on at least me, if not others as well.

**Comment by KieronQuinn** [comment]
> Wait you are going to discontinue the WHOLE app? The loyalty cards are not served by google at all (and arguably the most important feature)
> 
> I 100% understand your time thing though, I barely have enough time to deal with just using the apps I use and you have a lot of apps. Just FYI though, this app alone for me is reason enough to root your phone so just wanted you to know that its made a real positive impact on at least me, if not others as well.

That was the plan. [14 is adding support for showing them in the QAW](https://www.xda-developers.com/android-14-location-based-suggestions-loyalty-cards/), so my intention was to discontinue when that was released. Since it would continue working on old versions, it'd only stop being updated.

**Comment by rom4ster** [comment]
Under Stand Able (I just realized thats a compound word x3).  Looks like google finally got the memo and are doing *something* about this.
