### ISSUE TITLE
Wallet Database Improvement Tracking Issue

### ISSUE THREAD

**Issue by rom4ster** [KieronQuinn/ClassicPowerMenu#111]
I was reverse engineering the wallet app and I gained some very interesting insight. 

1.  The wallet app is mostly a shell. The real wallet and payment stuff is actually a part of google play services. 
2.  This means that everything, including saving and storing wallet data is actually handled by Google Play Services
3. The database CPM has been using is an auxiliary database by the looks of it, infact "tapandpay" is mostly under a section called "experiments" in teh source
4. Due to issues that I and some others on the forum seem to face, it may be that google will stop using the tapandpay database.
5. The google play services app has a database under its "pay" folder called valuables which has information that actually looks updated.

I feel that its important to make an issue on this, I am looking into it but its probably not gonna be fast as I stress

### I am a noob at android dev

This is why the issue is important so that people know about this. 

Ill update if i can get anything going with this. Or if someone else wants to do something, be my guest lol.

**Comment by rom4ster** [comment]
I can successfully connect to the database however there is a problem. The proto_bytes section does not want to serialize. Even using protoc  - - decode_raw on those bytes does not work. Invalid wire type. It could be because they are not protobuf format or maybe they are incomplete or something is missing or something. If anyone has any ideas would be helpful

**Comment by KieronQuinn** [comment]
The reason that database is not used is, because you found out, the data isn't readable. I think it's probably encrypted, as the JWTs are in the same table. 

It almost certainly contains the same data as is unencrypted in the database CPM actually uses, and while it may be a risk that Google stop using the tapandpay database, the same can be said for _any_ database. They could change format, decide to encrypt local data, anything which could break the reading. That is always a risk when reading local files with root. 

As for the Wallet app being a shell and the actual app residing in GMS, that's always been the case. I highly doubt it will change however, given it's been through no less than three branding and name changes, and stayed roughly the same in how it works. It's actually been highly beneficial to CPM, because the Wallet app (and previously Pay in both its forms as well) is not obfuscated. That means reading and reversing the protobuf is much, much easier. 

I'm not so sure about the experiments bit either - most of the models for the protobuf, the communication with GMS, the other logic, seems to reside in com.google.android.gms.tapandpay - not experiments.

**Comment by rom4ster** [comment]
The problem is that that my Tap and Pay database is no longer being updated for new cards. This is why I believe that Google is going to stop using this.

**Comment by KieronQuinn** [comment]
I added a transit ticket to my Wallet earlier today and it's been added to the valuables database, so there's nothing I can really suggest. If they are genuinely stopping using it (which I doubt) then there will probably be no alternative, as the other form is encrypted.

**Comment by rom4ster** [comment]
I do use a beta version of wallet. I may try opting out of the beta and see if that works.

**Comment by KieronQuinn** [comment]
There is no beta version of Google Wallet, do you mean the Play Services beta? I'm in that too, no difference.

**Comment by rom4ster** [comment]
Oh i see, there was one when they first released the Drivers licecence stuff, I guess its over now.

**Comment by Pfuenzle** [comment]
Are there any news here?
I am using Wallet version 23.44.582097972 and Play services 23.45.23, and while CPM is failing to load my loyalty cards, Smartspacer is successfully loading and using my Google Wallet loyalty cards with the Google Wallet Plugin. So it seems its still possible

**Comment by KieronQuinn** [comment]
> Are there any news here? I am using Wallet version 23.44.582097972 and Play services 23.45.23, and while CPM is failing to load my loyalty cards, Smartspacer is successfully loading and using my Google Wallet loyalty cards with the Google Wallet Plugin. So it seems its still possible

It's unlikely they'll ever work again, the rollout of encryption has since hit everyone (including me) and it's no longer possible to read them.

**Comment by Pfuenzle** [comment]
But why can the Wallet Smartspacer Plugin successfully read the Cards then? Isn't it also made by you? 

I installed both Smartspacer and CPM two days ago at the same time, and Wallet maybe 3 days earlier, so I doubt I still have the un-encrypted database on my device. Is there a way to check for it? 

CPM
![Screenshot_20231208-201413](https://github.com/KieronQuinn/ClassicPowerMenu/assets/11798845/14249217-f9b2-4279-96f1-8b9dfd84076c)


Smartspacer
![Screenshot_20231208-201400](https://github.com/KieronQuinn/ClassicPowerMenu/assets/11798845/be86e180-1abc-4855-ab7e-141f2873e8d7)

**Comment by KieronQuinn** [comment]
> But why can the Wallet Smartspacer Plugin successfully read the Cards then? Isn't it also made by you?
> 
> I installed both Smartspacer and CPM two days ago at the same time, and Wallet maybe 3 days earlier, so I doubt I still have the un-encrypted database on my device. Is there a way to check for it?
> 
> CPM ![Screenshot_20231208-201413](https://private-user-images.githubusercontent.com/11798845/289063684-14249217-f9b2-4279-96f1-8b9dfd84076c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMzgzODcsIm5iZiI6MTcwMjAzODA4NywicGF0aCI6Ii8xMTc5ODg0NS8yODkwNjM2ODQtMTQyNDkyMTctZjliMi00Mjc5LTk2ZjEtOGI5ZGZkODQwNzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDEyMjEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMGNmMzIzZmZhMDJhZmUzYzkyMmYwMDdiZTI5Nzc4NmVlYWM1OTk4NjI3MWYwZmRjZTRmNDA4MmYwNjRmNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wtUbfyAaPvhBcXcwQ6ygJj4lgC6Al8OxbvG_FpZalV8)
> 
> Smartspacer ![Screenshot_20231208-201400](https://private-user-images.githubusercontent.com/11798845/289063692-be86e180-1abc-4855-ab7e-141f2873e8d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMzgzODcsIm5iZiI6MTcwMjAzODA4NywicGF0aCI6Ii8xMTc5ODg0NS8yODkwNjM2OTItYmU4NmUxODAtMWFiYy00ODU1LWFiN2UtMTQxZjI4NzNlOGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDEyMjEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkZWU4ZWQ2YWIxYWQwNWU1YzZkMTQ5ZTZjODRiMDczNjg5Nzg2ZTA4YmM5NTk1NmQzOTYxMzdkYmY3OTM2NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3fAzrvkEFRUdE1tamhp5Zb5HoemVjTJEl3VcYkONbwM)

Because you log into your Google account for the Smartspacer plugin. That isn't feasible for CPM, the setup is different.

**Comment by rom4ster** [comment]
Your Google account stores your wallet information for everything except on device information such as health cards. You can actually get this information pretty easily as a Pdf. I thought it was not possible to get it in another format which is where I was stuck. I wonder if smart spacer is open source.

**Comment by KieronQuinn** [comment]
> Your Google account stores your wallet information for everything except on device information such as health cards. You can actually get this information pretty easily as a Pdf. I thought it was not possible to get it in another format which is where I was stuck. I wonder if smart spacer is open source.

It is, it's another one of my apps. The wallet code is in the plugin, on my SmartspacerPlugins repo. But like I say, it's a whole sign in and not worth it for just this IMO. Smartspacer itself is a good replacement for this feature until Google get their act together as it can show the loyalty card at a location and uses the same popup as CPM does to show it when locked

**Comment by rom4ster** [comment]
> > Your Google account stores your wallet information for everything except on device information such as health cards. You can actually get this information pretty easily as a Pdf. I thought it was not possible to get it in another format which is where I was stuck. I wonder if smart spacer is open source.
> 
> It is, it's another one of my apps. The wallet code is in the plugin, on my SmartspacerPlugins repo. But like I say, it's a whole sign in and not worth it for just this IMO. Smartspacer itself is a good replacement for this feature until Google get their act together as it can show the loyalty card at a location and uses the same popup as CPM does to show it when locked

I agree that there is no point trying to go after googles database. Losing battle tbh. 
 Also jeezus man you are EVERYWHERE. I just downloaded an app to get pixel like always listening song info and found out it was one of yours. I am going to play with smart spacer and see what fun I can have

**Comment by dariusz-goc** [comment]
> > Your Google account stores your wallet information for everything except on device information such as health cards. You can actually get this information pretty easily as a Pdf. I thought it was not possible to get it in another format which is where I was stuck. I wonder if smart spacer is open source.
> 
> It is, it's another one of my apps. The wallet code is in the plugin, on my SmartspacerPlugins repo. But like I say, it's a whole sign in and not worth it for just this IMO. Smartspacer itself is a good replacement for this feature until Google get their act together as it can show the loyalty card at a location and uses the same popup as CPM does to show it when locked

I think it's worth to make it work like the smart spacer. I would love to be able to display my loyalty cards in this app again.

**Comment by KieronQuinn** [comment]
> > > Your Google account stores your wallet information for everything except on device information such as health cards. You can actually get this information pretty easily as a Pdf. I thought it was not possible to get it in another format which is where I was stuck. I wonder if smart spacer is open source.
> > 
> > 
> > It is, it's another one of my apps. The wallet code is in the plugin, on my SmartspacerPlugins repo. But like I say, it's a whole sign in and not worth it for just this IMO. Smartspacer itself is a good replacement for this feature until Google get their act together as it can show the loyalty card at a location and uses the same popup as CPM does to show it when locked
> 
> I think it's worth to make it work like the smart spacer. I would love to be able to display my loyalty cards in this app again.

It is actually something I'm considering as Google have actually regressed the lock screen wallet experience by making it require unlock. I need to have time to do it though, which I don't have right now

**Comment by dariusz-goc** [comment]
Thank you for your consideration 👍

**Comment by Philip2809** [comment]
👀 
![image](https://github.com/user-attachments/assets/3c699293-749f-44e9-92a6-d95aa0be318c)
Working to fix this, making it optional, needing a signin to google, using smartspacerplugin as a base but need to redo some parts

**Comment by rom4ster** [comment]
> 👀 ![image](https://private-user-images.githubusercontent.com/51290462/363243823-3c699293-749f-44e9-92a6-d95aa0be318c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNDA4OTcsIm5iZiI6MTcyNTA0MDU5NywicGF0aCI6Ii81MTI5MDQ2Mi8zNjMyNDM4MjMtM2M2OTkyOTMtNzQ5Zi00NGU5LTkyYTYtZDk1YWEwYmUzMThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDE3NTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5YjkyNGMwN2E2NWYzZTZjNDMyYjgwZWU4MzdmNzlhY2IxNGFiMGQyYWMxY2EyNWZjOTYyMmJhNmE2NTFiYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IXd7O9mPPzs3brhxk6BXQiwfrVu0OifH89b1QkCctkI) Working to fix this, making it optional, needing a signin to google, using smartspacerplugin as a base but need to redo some parts

I'd love to test it out if you got any builds ready for testing.

**Comment by Philip2809** [comment]
> > 👀 ![image](https://private-user-images.githubusercontent.com/51290462/363243823-3c699293-749f-44e9-92a6-d95aa0be318c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNDA4OTcsIm5iZiI6MTcyNTA0MDU5NywicGF0aCI6Ii81MTI5MDQ2Mi8zNjMyNDM4MjMtM2M2OTkyOTMtNzQ5Zi00NGU5LTkyYTYtZDk1YWEwYmUzMThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDE3NTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5YjkyNGMwN2E2NWYzZTZjNDMyYjgwZWU4MzdmNzlhY2IxNGFiMGQyYWMxY2EyNWZjOTYyMmJhNmE2NTFiYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IXd7O9mPPzs3brhxk6BXQiwfrVu0OifH89b1QkCctkI) Working to fix this, making it optional, needing a signin to google, using smartspacerplugin as a base but need to redo some parts
> 
> I'd love to test it out if you got any builds ready for testing.

That would be very helpful, thanks! If you want you can test here:
https://github.com/Philip2809/ClassicPowerMenu/releases/tag/ALPHA-loyaltycards
There is A LOT of bugs and as I state there is no UI yet, I made this very quickly just to try it out. As I stated, all data is encrypted and stored on your device, source code in the same repo. Will continue to work on it!

**Comment by KieronQuinn** [comment]
Loyalty cards are now back in 1.9, closing :D

**Comment by Pfuenzle** [comment]
Thanks for implementing this feature, it is great to have it again :D

One question though, would it be possible with this implementation to also show time sensitive passes like tickets etc.?

Smartspacer added the feature in this commit https://github.com/KieronQuinn/SmartspacerPlugins/commit/96b7693de8e45aa55cf6d52b2142914ccb5d0fe4

Not sure if its too much work the implement here.

Thanks a lot anyways :D

**Comment by Pfuenzle** [comment]
Hm weird, my "Deutschlandticket" (German bus/train ticket) isn't shown on the carousel, and also doesn't show up under "Manage Accounts & Loyalty Cards" in the new update. 

It also didn't show up in Smartspacer in the Google Wallet (Static) section until the newest update there, now it shows up in the selection under "Transit Card", maybe thats a different type of card then?

**Comment by KieronQuinn** [comment]
If there's no time attached to it then yes, it will be treated as a generic pass and won't appear

**Comment by Pfuenzle** [comment]
Technically there is a time attached, the ticket is valid from 01.XX.2024 to 01.(XX+1).2024, but I guess its different than how movie or concert ticket times are handled in Wallet.

@Philip2809 Sorry for tagging you here, but you wrote the new Wallet Integration code.
Do you think it would be possible for you to add support for all kinds of valuables in CPM, like in the commit above for Smartspacer?
If not, no worries and thanks for your done work :)

**Comment by Philip2809** [comment]
The loyaltycards I fixed only cared about the loyaltycard type, all other types were discarded, it seams that the quick access wallet already showed some other types (which I did not know about). I can take a look into this as well, however I may not have a way to test this which could make it very hard for me to develop. I recently found how I can create test cards in google wallet and I can try to use that. But as I stated in some other thread, I am kinda busy the coming weeks but I can see what I can do. However I will look into the lock screen problem first as it kinda annoys me

For me at least CPM is very useful, as my card emulator app is always setting itself to be the default payment method I can't really use the built in quick access wallet that I can get from my lock screen, also accessing my device controls from anywhere by only pressing the power button is a really nice feature for me personally.

**Comment by rom4ster** [comment]
If you are looking into other types one type is perhaps a giftcard of some sort? I have a dunkin donuts refillable gift card that shows up in smartspacer but does not show up in quick access wallet. It useed to show up so I thought at first it was just a loyaltycard but apparently its different. Is there a place to find the type list? 

I would be willing to test the giftcard thing of course.

**Comment by KieronQuinn** [comment]
These are the types: https://github.com/KieronQuinn/SmartspacerPlugins/blob/main/googlewallet/src/main/proto/com/google/internal/tapandpay/v1/valuables/ValuableWrapper.proto

You can make fake ones of any of them with the Pass2pay app.

**Comment by rom4ster** [comment]
I thought health cards were stored on device so thats an interesting field. Looks like Gift card is a seperate type which would explain the dunkin not showing up.

**Comment by KieronQuinn** [comment]
There's no data in the Wallet app for health cards to come from the server so it's probably just a placeholder type in case it's ever used.
