### ISSUE TITLE
DenyList Requirements

### ISSUE THREAD

**Issue by Da-Boom** [KieronQuinn/ClassicPowerMenu#114]
Hi i tried to install this app, and after giving it root perms and enabling the exposed module through LSPosed, and rebooting. 

I quickly found that it would freeze with a blank screen upon attempting to launch any app (It also didn't show the purple google logo after unlock to indicate it was initializing Magisk modules) - I had to use in safe mode to uninstall all magisk modules. `adb shell magisk --remove-modules` to get the phone back into a useable state.

Phone: Pixel 3a
Android: 12
Firmware: SP2A.220505.008
LSPosed-v1.8.6-6712-zygisk-release
Magisk: 26.1 (26100)
Universal SafetyNet Fix: 2.4.0
Ramdisk: Yes
Zygisk: Yes
DenyList: Yes

I use the DenyList extensively for various apps - so just a question, are there any apps or (system or not) frameworks that cannot go on the DenyList when attempting to use ClassicPowerMenu? if there are, can you put them in the README?.

I might also try not installing the exposed module straight away and just using the accessibility system.

**Comment by KieronQuinn** [comment]
There are none, the Xposed module only runs for [SystemUI and CPM](https://github.com/KieronQuinn/ClassicPowerMenu/blob/main/app/src/main/java/com/kieronquinn/app/classicpowermenu/components/xposed/Xposed.kt#L38). I'm not sure what is happening on your device, but this module isn't to blame.
