### ISSUE TITLE
Error loading Loyalty Cards

### ISSUE THREAD

**Issue by Jnss98b** [KieronQuinn/ClassicPowerMenu#116]
Classic Power Menu version: 1.7
Device: Pixel Fold
Android version: 13
Google Play Services version: 23.25.18
Google Wallet version: 2.194.541972663

![image](https://github.com/KieronQuinn/ClassicPowerMenu/assets/24306400/a5d1d151-6689-48bd-b687-28cdc6124051)

**Comment by KieronQuinn** [comment]
This is the same root cause as #111 is tracking

**Comment by AlessandroTischer** [comment]
> This is the same root cause as #111 is tracking

Is this problem solvable? I have the same issue

**Comment by Jnss98b** [comment]
Prob not considering 111 is still open

**Comment by KieronQuinn** [comment]
It's not. Likely permanently broken as the new database is encrypted.
