### ISSUE TITLE
Reboot to recovery causes loop

### ISSUE THREAD

**Issue by flobere** [KieronQuinn/ClassicPowerMenu#121]
Using the reboot to recovery option works as expected, but upon rebooting to system from TWRP, _the phone only reboots back into recovery_. The only way to solve this is to recover the Para partition from a previous backup (thankfully I had one). No other combination of wiping and resetting fixed the issue.

It's a minor QoL feature, but i'd really love to use the recovery option in the power menu. The app is fantastic aside from this issue.

Running modified stock firmware android 11 on Daoqin f21 pro. Rooted and using the lsposed module.

Other details, may/may not be relevant: The factory power menu is a simple power off option and nothing else (i'm using an intent from a gesture navigation app to access the native android 11 power menu). The device has no physical volume keys and a very particular key combo for launching TWRP at boot.

**Comment by KieronQuinn** [comment]
The reboot recovery option [simply calls the system](https://github.com/KieronQuinn/ClassicPowerMenu/blob/88df6d49ea2076f922b76b30f1c04676d9f2383a/app/src/main/java/com/kieronquinn/app/classicpowermenu/ui/screens/powermenu/main/PowerMenuViewModel.kt#L109), it has no control over anything beyond that point. This isn't a CPM bug, but a bug in your firmware.

**Comment by flobere** [comment]
Understandable. Thanks for pointing to the relevant code, might help me out. Thankyou
