### ISSUE TITLE
Add opening and closing animation to the power menu

### ISSUE THREAD

**Issue by Fefedu973** [KieronQuinn/ClassicPowerMenu#124]

**Comment by KieronQuinn** [comment]
[It already has them](https://github.com/KieronQuinn/ClassicPowerMenu/blob/88df6d49ea2076f922b76b30f1c04676d9f2383a/app/src/main/java/com/kieronquinn/app/classicpowermenu/ui/activities/PowerMenuActivity.kt#L36). The system ignores them.

**Comment by Fefedu973** [comment]
> [It already has them](https://github.com/KieronQuinn/ClassicPowerMenu/blob/88df6d49ea2076f922b76b30f1c04676d9f2383a/app/src/main/java/com/kieronquinn/app/classicpowermenu/ui/activities/PowerMenuActivity.kt#L36). The system ignores them. 

It only works on the locks green any way to fix this ?

**Comment by KieronQuinn** [comment]
No. Like I said, the system ignores them.

**Comment by Fefedu973** [comment]
> No. Like I said, the system ignores them. 

Ok thanks anyway. Very very good app by the way thanks for everything!
