### ISSUE TITLE
Loyalty Cards doesn't working 

### ISSUE THREAD

**Issue by gurtnyi** [KieronQuinn/ClassicPowerMenu#129]
Hello there,

Loyalty Cards, and cards in Google Wallet doesn't show up when opening the power menu. Google Wallet is installed, and the option is enabled too in the classic power menu app. 
![Screenshot_20231028-202519_Classic Power Menu.png](https://github.com/KieronQuinn/ClassicPowerMenu/assets/73784167/c6517c82-515b-4ec8-98d2-af92ce073c5e)

Please fix the problem is possible.
Thanks a bunch,
gurtnyi

**Comment by KieronQuinn** [comment]
#111 

Loyalty cards will probably never work again, the database it was using is now encrypted. I've left the feature in for people using old versions of Wallet.
