### ISSUE TITLE
Didn't hook the Power Menu in LineageOS 20

### ISSUE THREAD

**Issue by Dian-Jiao** [KieronQuinn/ClassicPowerMenu#130]
It was still the orginal power menu.
![Screenshot_20231216-094014_Classic Power Menu](https://github.com/KieronQuinn/ClassicPowerMenu/assets/59251784/31002867-f0f1-498f-bc06-9dec8975b10e)

App version: 1.7.1
Android: 13 (LineageOS 20-20231201-NIGHTLY-sagit)
Device: Xiaomi Mi 6
Xposed: LSPosed1.9.2 (7024) (module enabled for System UI and Android Framework)
Magisk Delta: R657C2E65-kitsune (26403)

**Comment by KieronQuinn** [comment]
The Xposed module is community contributed, I don't support modifications that break it unless they are contributed by the community, sorry.
