### ISSUE TITLE
Possible non root solution

### ISSUE THREAD

**Issue by HamzehTamimi** [KieronQuinn/ClassicPowerMenu#131]
I have an idea for this to work on non rooted phones, by making it an assistant app and then with long press for assistant the power menu will pop up instead of google assistant similar to this app https://play.google.com/store/apps/details?id=color.dev.com.beige which makes makes the app an assistant app and shows the dock when power menu is long pressed.

**Comment by HamzehTamimi** [comment]
It won't work with shizuku?

**Comment by HamzehTamimi** [comment]
Like this app: https://github.com/ryuunoakaihitomi/rebootmenu

**Comment by KieronQuinn** [comment]
The power options would, device controls & quick access wallet would not. It would be pointless.
