### ISSUE TITLE
Accessibility service and package installer?

### ISSUE THREAD

**Issue by IzzySoft** [KieronQuinn/ClassicPowerMenu#134]
In January my scanner got a few additional checks. So on today's release it reported:

```
! repo/com.kieronquinn.app.classicpowermenu_172.apk declares intent-filter(s): android.accessibilityservice.AccessibilityService
! repo/com.kieronquinn.app.classicpowermenu_172.apk declares sensitive permission(s): android.permission.REQUEST_INSTALL_PACKAGES android.permission.QUERY_ALL_PACKAGES android.permission.CAMERA
```

Could you please clarify what for Accessibility Services are used – and what packages your app wants to install? Further: Concerning `CAMERA`, a screenshot shows what could be a QR code scanner. Is it? And what for does the app need `QUERY_ALL_PACKAGES`?

Thanks in advance!

**Comment by KieronQuinn** [comment]
Accessibility is used to know when the power menu is open. Install packages is used for updates. 

QUERY_ALL_PACKAGES is for device controls, camera does indeed come from the QR library.

**Comment by IzzySoft** [comment]
Thanks again! As with Ambient, same questions concerning the updater here (and same hints for the `DEPENDENCY_INFO_BLOCK`).

What I did not understand: `QUERY_ALL_PACKAGES` is for listing all installed apps. I must admit I'm not using ClassicPowerMenu myself, so my question might sound a little weird: but what does that have to do with "device controls"? I probably miss what they are :zany_face:

**Comment by IzzySoft** [comment]
And am I assuming correctly that `android.permission.REQUEST_INSTALL_PACKAGES` is again an enforced self-updater here, @KieronQuinn? :cry:

**Comment by KieronQuinn** [comment]
> And am I assuming correctly that `android.permission.REQUEST_INSTALL_PACKAGES` is again an enforced self-updater here, @KieronQuinn? 😢

Yes, as has always been the case. All of my apps have this, it's not new.
