### ISSUE TITLE
power menu doesn't get applied after first boot until it is triggered manually

### ISSUE THREAD

**Issue by FurhadTheNerd** [KieronQuinn/ClassicPowerMenu#137]
I've been using classic power menu for around 2 years now, this is such an awesome project!
i rely on it so my phone cannot be turned off from the lock screen
but sadly when i try to access the power menu after a reboot or whatever, the default power menu shows up, then if i exit it and then try again, the classic power menu will stay until the next reboot
that's no big deal but the problem is that i forgot to manually trigger it sometimes
is it caused by my OS or is it a known limitation?
I'm running stock android 14 security patch of april 2024 on a pixel 6 (AP1A.240405.002)
but I've had that since forever, i don't think its related anyways
and thanks for developing such a great solution!

**Comment by KieronQuinn** [comment]
This is normal, it's how the hooking works.
