### ISSUE TITLE
Doesn't Open over Lock Screen

### ISSUE THREAD

**Issue by dariusz-goc** [KieronQuinn/ClassicPowerMenu#149]
With the latest update 1.9, that brought loyalty cards back there's a new bug introduced. When on Locked Screen and trying to open the power menu CPM flashes and disappears, requiring unlock or fingerprint. Only works when the phone is unlocked.

Sidenote:
Another minor bug I noticed is when "Show loyalty cards" is disabled and enabled again, the switch for "allow loyalty cards on lockscreen" doesn't work. Only the toggle, somehow tapping the toggle's label makes a switch. The same it's true for all loyalty cards related switches when toggling "Show wallet" off and on.

**Comment by KieronQuinn** [comment]
#143
