### ISSUE TITLE
Home tiles do not have the same border radius as the power buttons

### ISSUE THREAD

**Issue by WampireDev** [KieronQuinn/ClassicPowerMenu#150]
The power buttons and the smart home buttons have a different border radius I don't know if this is not intended, or even possible to adjust. But if it is then please fix. (It would be cool if ppl could ajust it but then this would be a feature request so i dunno)
![Screenshot_20240913-173833_Classic Power Menu](https://github.com/user-attachments/assets/0207cd22-40a6-4f4c-a360-c74b79ecd96e)

**Comment by KieronQuinn** [comment]
Working as intended.
