### ISSUE TITLE
Can't enable Accessibility Service

### ISSUE THREAD

**Issue by jolaviska** [KieronQuinn/ClassicPowerMenu#152]
I'm unable to enable the accessibility service as it's grayed out on my Oneplus device, Android v14

Any ideas? 

![Screenshot_2024-09-14-12-15-25-19_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/17cbfd37-015d-4425-a339-0f36e8db6f4c)

![Screenshot_2024-09-14-13-54-23-82_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/025fd06a-4398-4391-9570-d3f35f3fc1cf)

**Comment by KieronQuinn** [comment]
https://support.google.com/android/answer/12623953?hl=en-GB
