### ISSUE TITLE
Cannot use with just accessibility service on android 14.

### ISSUE THREAD

**Issue by AlexS2412** [KieronQuinn/ClassicPowerMenu#153]
current version has conflict with current lsposed which causes it to prevent pixelxpert from loading its own config after reboot. when trying to just use the accessibility service the overlay appears and immediately puls itself down and vanishes.

**Comment by KieronQuinn** [comment]
#143

**Comment by AlexS2412** [comment]
why did you close this? the lsposed conflict is relevant and important @KieronQuinn

**Comment by KieronQuinn** [comment]
PixelXpert is working fine with it on Android 15, you may need to downgrade to a version that is intended for 14 or wait for the 15 update to drop. It's not a CPM issue.

**Comment by AlexS2412** [comment]
> PixelXpert is working fine with it on Android 15, you may need to downgrade to a version that is intended for 14 or wait for the 15 update to drop. It's not a CPM issue.

this conflicts in newer LSPOSED. somehow a conflict was created when it went to the new parasitic manager that didnt exist before this. classic power menu is now incompatible as there is a conflict with the hooks it makes that prevents pixelxpert from accessing uts saved configs and applying them.

**Comment by KieronQuinn** [comment]
Like I said, there is no issue with the newest version of Android, PixelXpert and the [right LSPosed version](https://github.com/JingMatrix/LSPosed). 

CPM is not the issue here.
