### ISSUE TITLE
Problem getting in Cards

### ISSUE THREAD

**Issue by mjain234** [KieronQuinn/ClassicPowerMenu#155]
I am having a problem regarding adding cards through Classic Power Menu app as you can see [here](https://github.com/user-attachments/assets/be95bd6e-7e29-4854-bd4f-c5504e4740ae).
What is the problem causing this as it has been there for a longer period for me.

**Comment by KieronQuinn** [comment]
The cards are loaded using the Quick Access Wallet API, it's possible that this API is not available on your device. Which device, firmware/ROM and Android version is it?

**Comment by mjain234** [comment]
Device: Nothing Phone 1 

Android: Android 14

**Comment by KieronQuinn** [comment]
In that case it's likely just not compatible. I'll reopen if you can get logs showing it's a CPM issue.

**Comment by mjain234** [comment]
![11_10-12-33-16_406.zip](https://github.com/user-attachments/files/17338989/11_10-12-33-16_406.zip)

**Comment by KieronQuinn** [comment]
> QuickAccessWalletService manifest entry mis-configured

Indeed your firmware does not support Quick Access Wallet
