### ISSUE TITLE
The close issue is still not fixed unfortunately 

### ISSUE THREAD

**Issue by Fefedu973** [KieronQuinn/ClassicPowerMenu#160]
I'm on 1.9.1 on a pixel 8 pro running android 15 (AP41.240823.009) (beta)
And I still have the same issue, the classic power menu is crashing on the overlay opening.

https://github.com/user-attachments/assets/aca1132f-f294-46e2-8e54-c08f1a8f0d1e

**Comment by FurhadTheNerd** [comment]
its working just fine on android 15 (stable) (AP3A.241005.015) (pixel 6 stock with magisk) after updating to v1.9.1
update to the stable release and see if that helps

**Comment by Fefedu973** [comment]
> its working just fine on android 15 (stable) (AP3A.241005.015) (pixel 6 stock with magisk) after updating to v1.9.1
> update to the stable release and see if that helps 

I'm on the beta channel so I can't, I just said that it doesn't work on the beta channel, what's the point to return to stable if I want to report for the beta ???

**Comment by FurhadTheNerd** [comment]
my apologies @Fefedu973 i thought you were going to switch to the stable channel

**Comment by Fefedu973** [comment]
Nah because I can't

**Comment by KieronQuinn** [comment]
This is not the same issue, please provide a log of the crash.

**Comment by KieronQuinn** [comment]
Please check version 1.9.2 as it may be the same crash as was fixed

**Comment by dariusz-goc** [comment]
> Please check version 1.9.2 as it may be the same crash as was fixed

On Android 14 after updating to 1.9.2 the app is not starting up and the power menu is crashing. Downgrading to 1.9.1 fixes it. The crash was introduced in 1.9.2.

**Comment by KieronQuinn** [comment]
> > Please check version 1.9.2 as it may be the same crash as was fixed
> 
> On Android 14 after updating to 1.9.2 the app is not starting up and the power menu is crashing. Downgrading to 1.9.1 fixes it. The crash was introduced in 1.9.2.

Then, once again, I will need a log.

**Comment by dariusz-goc** [comment]
> > > Please check version 1.9.2 as it may be the same crash as was fixed
> > 
> > 
> > On Android 14 after updating to 1.9.2 the app is not starting up and the power menu is crashing. Downgrading to 1.9.1 fixes it. The crash was introduced in 1.9.2.
> 
> Then, once again, I will need a log.

Sure, what kind of log? Logcat?

**Comment by KieronQuinn** [comment]
> > > > Please check version 1.9.2 as it may be the same crash as was fixed
> > > 
> > > 
> > > On Android 14 after updating to 1.9.2 the app is not starting up and the power menu is crashing. Downgrading to 1.9.1 fixes it. The crash was introduced in 1.9.2.
> > 
> > 
> > Then, once again, I will need a log.
> 
> Sure, what kind of log? Logcat?

Yes please

**Comment by dariusz-goc** [comment]
> > > > > Please check version 1.9.2 as it may be the same crash as was fixed
> > > > 
> > > > 
> > > > On Android 14 after updating to 1.9.2 the app is not starting up and the power menu is crashing. Downgrading to 1.9.1 fixes it. The crash was introduced in 1.9.2.
> > > 
> > > 
> > > Then, once again, I will need a log.
> > 
> > 
> > Sure, what kind of log? Logcat?
> 
> Yes please

[StartupHang.txt](https://github.com/user-attachments/files/17452464/StartupHang.txt)
[PowerMenuCrash.txt](https://github.com/user-attachments/files/17452465/PowerMenuCrash.txt)

**Comment by KieronQuinn** [comment]
Looks like your install is somehow corrupted, uninstall and reinstall. The APK definitely includes the classes your log is claiming it doesn't.

**Comment by dariusz-goc** [comment]
> Looks like your install is somehow corrupted, uninstall and reinstall. The APK definitely includes the classes your log is claiming it doesn't.

Ok, that's crazy, but you gave me an idea. I re-downloaded 1.9.2 and then went into lsposed manager and re-optimized CPM and now it started fine and power menu works too 🤯 Thanks for your help.

**Comment by KieronQuinn** [comment]
In that case, closing

**Comment by PowerUser64** [comment]
I had this exact same problem. I think the app gets into a broken state if you go through the setup flow and give it root privileges before giving it Xposed permissions and rebooting.

Correct:

1. Install
2. Open LSposed and grant Xposed permission for CPM
3. Reboot (CPM now has Xposed but not root)
4. Open CPM and grant SU access
5. Reboot

Incorrect:

1. Install (or reinstall over an existing broken installation)
2. Open CPM and go through the setup flow to grant SU access
3. Reboot (CPM now has root but not Xposed)
4. Open LSposed and grant Xposed permission for CPM
5. Reboot

I think this *might* also be incorrect:

1. Install (or reinstall over an existing broken installation)
2. Open CPM and grant SU access
2. Open LSposed and grant Xposed permission for CPM
4. Reboot

... and I think it's also incorrect if you switch steps 2 & 3 here.


Uninstalling and going through the first list of steps that I wrote above seems to fix it if you went through the wrong order of steps to bring with. This is what seemed to happen to me at least. Initially I did the steps in the second order I listed here, which I think is what broke it. I repeated them in the first order and that fixed it.

Also related: #165
