### ISSUE TITLE
CPM Xposed module causes all other Xposed modules to stop working on newer LSposed builds

### ISSUE THREAD

**Issue by i5lee8bit** [KieronQuinn/ClassicPowerMenu#161]
This issue doesn't happen unless you are using the newest builds of LSposed, e.g. JingMatrix fork 1.10.1 or NPM 1.9.2-7074 (or maybe 7072?) and higher. JingMatrix fork can be found here in GitHub (link below) and NPM builds (which I believe are by the original LSP devs) can be found: https://t.me/rormzhstjxm/

I think this may be important since people will slowly move on to these newer LSP builds, and hopefully won't need to have as much headache as I did trying to figure out what's wrong lol.

So anyway, this is a weird one here, but I've narrowed it down to the enabling of CPM's Xposed module causing all other Xposed modules to stop working, even though logs seem to indicate everything is fine. I initially opened an issue on the latest version (1.10.1, released earlier today) of JingMatrix's LSposed fork. Here is the issue I posted with more details - https://github.com/JingMatrix/LSPosed/issues/64

I also noticed this issue starting with the LSposed-npm builds starting with 7074 or so (iirc basically since they introduced the new parasitic manager, which has the nice ability to disable log watchdog for better hiding), although when I first noticed this was over a month ago and I didn't figure out at the time it had anything to do with CPM module being enabled, so I always just rolled back to JingMatrix 1.10.0 build.

I've now isolated the issue that simply disabling CPM's Xposed module makes everything work again, and I can now use the current LSP builds.

Hopefully it's a fairly easy fix for you. I actually still love this app and consider it a must-have for Pixel phones! Let me know if there's any other logs or info you could use and I'll try to do it asap. The issue I opened on JingMatrix's GitHub has a lot of extra info you may find useful. Thanks again as always!

**Comment by KieronQuinn** [comment]
Not a CPM issue (see comment in linked issue)
