### ISSUE TITLE
Screenshot tile doesn't work.

### ISSUE THREAD

**Issue by MillionsToOne** [KieronQuinn/ClassicPowerMenu#164]
Tapping the screenshot tile doesn't take a screenshot. It just closes the power menu.

**Comment by KieronQuinn** [comment]
The screenshot button simply invokes the system with the screenshot key event: https://github.com/KieronQuinn/ClassicPowerMenu/blob/e17f14a85f85d4eefabaf847abfadd1af32291c1/app/src/main/java/com/kieronquinn/app/classicpowermenu/service/root/impl/CPMRootServiceImpl.kt#L151

If your device does not support this, then there is nothing I can do. This is the standard, it's not my fault if not every Android modification supports it.
