### ISSUE TITLE
Shutdown menu closes when trying to open it

### ISSUE THREAD

**Issue by Coll147** [KieronQuinn/ClassicPowerMenu#165]
Android 15 (Crdroid 11)

https://github.com/user-attachments/assets/68405c0b-efb7-4795-adc8-3740d6f966f1

**Comment by KieronQuinn** [comment]
Which version of the app?

**Comment by Coll147** [comment]
> Which version of the app?

Sorry for not mentioning it, it's version 1.9.2

**Comment by KieronQuinn** [comment]
Try uninstalling & reinstalling, and rebooting. If that doesn't fix it, nothing I can do. This was already fixed in 1.9.2.

**Comment by Coll147** [comment]
> Try uninstalling & reinstalling, and rebooting. If that doesn't fix it, nothing I can do. This was already fixed in 1.9.2.

It seems that reinstalling fixed the problem. Thanks.
