### ISSUE TITLE
The original shutdown menu appears once

### ISSUE THREAD

**Issue by Coll147** [KieronQuinn/ClassicPowerMenu#166]
The original shutdown menu appears once after each reboot, after that time the classic power menu appears. I don't know if it's a limitation of the application or a bug. Thanks
App version 1.9.2
Android 15 (Crdroid 11-beta)

https://github.com/user-attachments/assets/c0278a7e-1130-41b3-beb3-ceb9c830d0d5

**Comment by RedCrafter07** [comment]
Same issue here (A15 too), although I don't really mind opening my power menu once. I assume it's a limitation as it is the first time the power menu loads. But I'm not sure on that.

**Comment by RedCrafter07** [comment]
#137 is the same issue you described.

**Comment by KieronQuinn** [comment]
It is, and you found the issue I was about to link. Normal behaviour.
