### ISSUE TITLE
[Request] Support Custom ROM (Color OS)

### ISSUE THREAD

**Issue by dathtd119** [KieronQuinn/ClassicPowerMenu#167]
Hi KieronQuinn, this is a great tool. I noticed that when I used it on an AOSP based ROM _(Evolution X on my SS Note 10+ for example)_ , it worked flawlessly. But not on my heavy customized ROM (Color OS 14 A14 based).

Since on Color OS, it has its own Power Menu, and I see this quite a problem to work with this Mod.

My questions are:

1. I want to know how this app intercepts with a normal power menu.
2. My color OS is a rooted one, so how can I view the log/detail, or how does the system interact/detect/watch the power key being pressed?

_Thanks so much._

**Comment by KieronQuinn** [comment]
Custom ROMs that are far enough from AOSP to not work are only supported by community contributions. Look at the MIUI/HyperOS pull requests for examples of that. I won't be adding support myself however.

**Comment by dathtd119** [comment]
> My questions are:
> 1. I want to know how this app intercepts with a normal power menu.
> 2. My color OS is a rooted one, so how can I view the log/detail, or how does the system interact/detect/watch the power key being pressed?



Thanks for the respond, actually I don't need to support custom ROM. My main questions remain the same, I need the answer for these questions so that I can try on my own then.

**Comment by KieronQuinn** [comment]
> > My questions are:
> > 
> > 1. I want to know how this app intercepts with a normal power menu.
> > 2. My color OS is a rooted one, so how can I view the log/detail, or how does the system interact/detect/watch the power key being pressed?
> 
> Thanks for the respond, actually I don't need to support custom ROM. My main questions remain the same, I need the answer for these questions so that I can try on my own then.

The answer to both is in the source code.
