### ISSUE TITLE
Androud 11 CPM issue

### ISSUE THREAD

**Issue by jekv2** [KieronQuinn/ClassicPowerMenu#168]
Clasaic power menu has a delayed startup time, it takes 2 times or 3 to hold power for cpm to register then bubble msg says cpm has been gramted root permission.

Not sure why takes few times for it to actually activate the custom power menu even though the app has been granted root permission.

Magisk v28 & latested lsposed. Latest CPM.

**Comment by jekv2** [comment]
![Screenshot_20241202-203457](https://github.com/user-attachments/assets/ac9f77ee-1932-4403-96f7-22a51deba531)

**Comment by KieronQuinn** [comment]
Probably the same as #137, the hooking may be slower in some cases. If it works eventually, there isn't anything more I can do.
