### ISSUE TITLE
Adding a shortcut so quick tap can be assigned to open the app's power menu interface

### ISSUE THREAD

**Issue by Jnss98b** [KieronQuinn/ClassicPowerMenu#18]
Something like this
![Screenshot_20211101-230442](https://user-images.githubusercontent.com/24306400/139865463-69047f70-ec65-458a-a536-febab6ec0374.png)

**Comment by KieronQuinn** [comment]
Good idea. It'd work with Tap, Tap too with that.

**Comment by KieronQuinn** [comment]
Added in 1.4
