### ISSUE TITLE
Non-Root Version

### ISSUE THREAD

**Issue by csm10495** [KieronQuinn/ClassicPowerMenu#19]
Hey there,

This is a wonderful idea. Any chance for a version that doesn't require root? I found an app that can remap the volume buttons if pressed at the same time to do something (without root).

Could a non-root version of this app work via pressing both volume buttons at the same time to open the power menu?

I may be under thinking this, maybe more than just power button hooking requires root.

Regardless this type of thing without root would be great. Thanks!

**Comment by KieronQuinn** [comment]
Not possible, the hack to interact with device controls and quick access wallet needs root, so it would be pretty useless without that.

**Comment by Dhyfer1** [comment]
> Not possible, the hack to interact with device controls and quick access wallet needs root, so it would be pretty useless without that.

I understand. But ClassicPowerMenu might be able to work on non-rooted devices with the help of [Shizuku](https://shizuku.rikka.app/) ? I don't know, it's just an idea. 🤔

**Comment by KieronQuinn** [comment]
> > Not possible, the hack to interact with device controls and quick access wallet needs root, so it would be pretty useless without that.
> 
> @KieronQuinn I understand. But ClassicPowerMenu might be able to work on non-rooted devices with the help of [Shizuku](https://shizuku.rikka.app/)? As you can see, Shizuku is a requirement for non-rooted devices in your [AmbientMusicMod](https://github.com/KieronQuinn/AmbientMusicMod/) repo. I don't know, it's just an idea. 🤔

No, as stated above it needs root. Shizuku is not root.
