### ISSUE TITLE
Make blur command easy to access

### ISSUE THREAD

**Issue by lavin-a** [KieronQuinn/ClassicPowerMenu#21]
Allow copying the blur command from the FAQ section in the app, currently text cannot be highlighted

Also, change the command to one line since some terminals don't support pasting multi line commands

`su -c resetprop ro.surface_flinger.supports_background_blur 1
pkill -TERM -f com. android.systemui
`

**Comment by KieronQuinn** [comment]
Text is selectable in 1.4. 

I don't like advising to use `su -c` like that as it is less obvious to the user what it's doing, having it split across lines makes it more readable.
