### ISSUE TITLE
Not working perfectly

### ISSUE THREAD

**Issue by mjain234** [KieronQuinn/ClassicPowerMenu#22]
I am facing an issue with Classic Power Menu, whenever I am clicking on power Menu, the screen gets locked and the power menu is opening
https://drive.google.com/file/d/1eY6lYtCw3K4iVEBR6QfHXrGgm4sgS6iT/view

**Comment by KieronQuinn** [comment]
Please provide more information. What device, what Android version, are you using the Xposed method or accessibility?

**Comment by mjain234** [comment]
Device: Realme 2 Pro
Android version: Android 12
I tried with both accessibility and Xposed module, but whenever pressing
power menu, the screen getting locked and then power menu is showing.
Check out this video

**Comment by KieronQuinn** [comment]
Yes, I saw the video. As the behaviour is happening with the accessibility service too, the cause is almost definitely the system, but one last question - can you unlock with fingerprint after the screen gets "locked"? I can't see behind the clear notifications circle on your video.

**Comment by mjain234** [comment]
Yaa, I can unlock my screen. So, what should I do now?

**Comment by KieronQuinn** [comment]
If you can unlock the screen, CPM is definitely not at fault. There's no code to lock the screen but not put it into lockdown mode, so it is not to blame. 

There is nothing I can do, your issue is caused by some weird system behaviour.
