### ISSUE TITLE
Add an option to use a solid background instead of a blurred background

### ISSUE THREAD

**Issue by Jnss98b** [KieronQuinn/ClassicPowerMenu#26]
The background should follow material you too, maybe using the same shade as the notification panel or even better, using a 2 tone design like the calculator app which fits the current design of the app

![Screenshot_20220119-195636](https://user-images.githubusercontent.com/24306400/150270579-ef153203-2362-4af1-bd70-4ca59e76b502.png)
![Screenshot_20220119-195634](https://user-images.githubusercontent.com/24306400/150270581-976cd1c1-93d3-4ab9-b555-6b06cd5b66d2.png)

**Comment by KieronQuinn** [comment]
Added in 1.4
