### ISSUE TITLE
Show two apps with controls at the same time

### ISSUE THREAD

**Issue by ministryofsillywalks** [KieronQuinn/ClassicPowerMenu#29]
I have controls from both home assistant and tinycam pro integrated in the powermenu. However (as it was in Android 11) I have to switch between the two apps using the dropdown menu.
Is it at all possible to have the control from both apps shown at the same time? I only use a few buttons so it would easily fit on the screen.
Maybe you can somehow add this as an option?
Thanks!

**Comment by KieronQuinn** [comment]
This is a limitation of the Controls library that's in AOSP, it's only built to bind to one app at once. It would take significant rewrite to change that, which I'm not prepared to do so I'm going to say this is out of scope, but anyone is welcome to fork the project and give it a shot.
