### ISSUE TITLE
Not working on Android 12L

### ISSUE THREAD

**Issue by HeyItsJono** [KieronQuinn/ClassicPowerMenu#31]
Hiya, just installed Android 12L on my Pixel 5 (12.1.0 (SP2A.220305.012, Mar 2022)) and have found that background blur and the Classic Power Menu module itself are both non-functional. I'm using Classic Power Menu 1.3.1 via LSPosed 1.7.2, with the module enabled and hooking com.android.systemui as well as System Framework. This is all running on Magisk 24.3. The accessibility service also unfortunately does not work. Any help would be greatly appreciated!.

**Comment by KieronQuinn** [comment]
#30 

Known issue anyway, already reported on the xda thread.
