### ISSUE TITLE
Menu immediately quits after 1.4 update

### ISSUE THREAD

**Issue by Chaphasilor** [KieronQuinn/ClassicPowerMenu#33]
Hi,

just update to v1.4 and now when holding the power button, the menu either shows for a fraction of a second an then disappears or it doesn't show at all.

Here's a short video:

https://user-images.githubusercontent.com/18015147/159114373-3e297878-047a-4f54-b94f-e158bcf435f7.mp4

I'm running Android 12 (Pixel Experience 12) on a rooted OnePlus 5, if that helps.

**Comment by C0unt-zero** [comment]
I probably have the same problem.

https://user-images.githubusercontent.com/82859690/159119051-018bd583-7ab9-4f11-9491-107c92062013.mp4

It crashes when I enable Quick Access Wallet.
The crash will not occur unless Quick Access Wallet is enabled.
The previous version (1.3.1) worked fine.
I use Android 12 (DerpFest) on OnePlus5.

**Comment by Chaphasilor** [comment]
FYI I have quick access wallte disabled but it's still happening :)

**Comment by EugeneDP89** [comment]
For me it's not even appearing, restarted phone several times, enabled/disabled it. Previous versions worked fine.

**Comment by bjevers** [comment]
Same here. Shows for a split second, then crashes. Pixel 6 Pro on beta 12L.

**Comment by ohayoubaka** [comment]
Same problem here, running Android 12 (stock ROM) on a Sony Xperia 1 III.

**Comment by KieronQuinn** [comment]
Fixed in 1.4.1

Just FYI, it would be nice if someone sent a crash log for this. Not complaining if you can't or don't know how to, but just saying it happens to you too isn't exactly that useful for fixing it.
