### ISSUE TITLE
Appear Animation advise

### ISSUE THREAD

**Issue by Sparkingdog** [KieronQuinn/ClassicPowerMenu#36]
Current appear amination is float from below, can you add another option for intro animation like fade in , rotate in or something else?
BTW
Thanks for your work, the new version 14.1 did not work for me so I downgraded to 13.1 and it work flawlessly.

**Comment by KieronQuinn** [comment]
The animation is set to fade in already: https://github.com/KieronQuinn/ClassicPowerMenu/blob/e3cd7efa1f4182c343d15ba30d3781b5996c24f1/app/src/main/java/com/kieronquinn/app/classicpowermenu/ui/activities/PowerMenuActivity.kt#L36

if it's not working for you then your device is ignoring it and I can do nothing.
