### ISSUE TITLE
Power menu shows up only in classic power menu app

### ISSUE THREAD

**Issue by Manasx100** [KieronQuinn/ClassicPowerMenu#40]
Power menu shows up only whent the classic power menu Is open in the launcher or any other app when I hold the power button it just vibrates it worked perfectly fine but now it doesn't work normally and the default power menu doesn't show up to when classic power menu gets root privileges from magisk
I'm using lsposed zygisk

**Comment by KieronQuinn** [comment]
What device?

**Comment by Manasx100** [comment]
Poco x3 pro

**Comment by KieronQuinn** [comment]
Almost definitely caused by MIUI's restrictions. Nothing I can do.

**Comment by Manasx100** [comment]
It worked before I don't update anything and I'm with root lsposed

**Comment by Manasx100** [comment]
MIUI 13

**Comment by Manasx100** [comment]
Fixed draw over other apps in background wasn't enabled
