### ISSUE TITLE
Not working on MIUI 13

### ISSUE THREAD

**Issue by Asfaltinho** [KieronQuinn/ClassicPowerMenu#43]
It simply open the default Power menù on MIUI 13 (i'm on .eu weekly 22.4.21) also with lsposed module.

**Comment by KieronQuinn** [comment]
MIUI is not fully supported, it requires community support. If it doesn't work, there's nothing I can do.

**Comment by Rayrsn** [comment]
is there still no plan to add support for miui?

**Comment by KieronQuinn** [comment]
No plan from me, as I said in the previous comment it requires community support. I do not have a MIUI device.

**Comment by Rayrsn** [comment]
I have one, is there any way i can help?

**Comment by KieronQuinn** [comment]
It needs a pull request like this: https://github.com/KieronQuinn/ClassicPowerMenu/pull/24, with either a newer version check or if that doesn't work, a full updated implementation for MIUI
