### ISSUE TITLE
[Feature request]: add item "Flashlight"?

### ISSUE THREAD

**Issue by LeeBinder** [KieronQuinn/ClassicPowerMenu#44]
Hi Kieron. Thank you for ClassicPowerMenu. Can you add an option to add the "Flashlight" button?

**Comment by KieronQuinn** [comment]
The power options are not intended to be toggles, so no I won't be added flashlight. I suggest you use an app like Power Toggles to add that to the Controls UI

https://play.google.com/store/apps/details?id=balti.powermenu.shortcuts

**Comment by LeeBinder** [comment]
Hi Kieron. I've been aware of SayantanRC's Power menu controls for Android 11+. Three reasons why I shun to use it:
- it would add another app
- the dev hasn't updated it since 2021-06
- he hasn't been replying in his app's thread @ XDA anymore (his last posting there was on June 2021)

so it seems like abandonware for now. Well, bummer you don't want to add such options. Maybe you think it over again some time in the future.

**Comment by KieronQuinn** [comment]
Unfortunately toggles are a slippery slope, I have the exact same problem with Tap, Tap. If you add one toggle, you get requests for every workflow under the sun. It's far better to be left to third party apps when there's an API available.

**Comment by LeeBinder** [comment]
LOL OK, gotcha. Well, still better than getting requests for every workflow in the milky way ;)
