### ISSUE TITLE
CPM doesn't work on Android 13 beta 2

### ISSUE THREAD

**Issue by Rolodo** [KieronQuinn/ClassicPowerMenu#45]
Android version: 13 beta 2
Lsposed version: zygisk 1.8.3 (6552)

Since A13B2 we cannot grant permission for "Accessibility Service" so we are forced to use the root method with lsposed.

When trying to trigger the menu the normal power menu is displayed instead of CPM.

Thanks

**Comment by KieronQuinn** [comment]
You can still grant access to accessibility in the meantime by allowing unrestricted settings access in App Info, or installing via ADB or a session based installer.

**Comment by jiggs82** [comment]
Unfortunately cpm is not working for me either on a13 beta 2 P6Pro even with accessibility settings enabled

**Comment by KieronQuinn** [comment]
You will need to disable the Xposed module probably (+ reboot), it is definitely working using just accessibility

**Comment by jiggs82** [comment]
Yeah that worked but now the default power menu shows before cpm lol anyway to now show it without lsposed?

**Comment by KieronQuinn** [comment]
No, that's why the Xposed module exists. I'll fix it when I get the time.

**Comment by jiggs82** [comment]
Oh ok gotcha! Thanks for the quick replies and looking forward to the update 👍🏻

**Comment by Rolodo** [comment]
Thanks for the update :)

**Comment by KieronQuinn** [comment]
Support for B3 has been added in 1.5. Update to B3 first, as it will crash on B2 due to a different issue.
