### ISSUE TITLE
Can't see new loyalty cards in the power menu

### ISSUE THREAD

**Issue by Perseo2499** [KieronQuinn/ClassicPowerMenu#49]
Hi, 

Thanks in advanced for the new features. The last update feels great. 

The thing is that when I add a new loyalty card to Gpay, the card is not appearing in the power menu. Also, if I delete an old card, the card will remain in the menu. 

I tried formating the data of the app, unisntalling the module and the app and reintsalling it, but nothing works.

**Comment by ohmybahgosh** [comment]
Not sure if this the same issue, but it's definitely related...this is the error I get...removed all my loyalty cards and added from scratch as well..no dice...kept getting this error:

![92DJ16e](https://user-images.githubusercontent.com/77786782/176041599-b9057358-a26b-4d5e-8414-4a2f58a723ed.png)

**Comment by KieronQuinn** [comment]
Unable to reproduce this, thought I could but I was mistaken. Make sure you're using Google Wallet (formerly Google Pay) **not** GPay, and if you're using Pass2Pay you **must** be adding them as Loyalty cards. **not** the default "offer" option (which is what I was doing wrong for what I thought was the broken card).

I will reopen if reproducible steps are given.
