### ISSUE TITLE
Classic Power Menu not autostart

### ISSUE THREAD

**Issue by lublak** [KieronQuinn/ClassicPowerMenu#53]
Currently (Android 12.1 Lineageos) the power menu not autostart.
I need to manually start the app to apply the effect.
I enabled Classic Power Menu in LSPosed (com.android.systemui) and also allow super user.

**Comment by KieronQuinn** [comment]
If you're using the Xposed module, it hooks SystemUI. If it's not opening first time, that's the hooking happening - close and re-open the menu (you only need to do it once)
