### ISSUE TITLE
ClaasicPowerMenu not working after last update

### ISSUE THREAD

**Issue by bzz11g** [KieronQuinn/ClassicPowerMenu#56]
Device: Pixel 6
OS: Stock 12.1.0 (SQ3A.220705.003, Jul 2022)
Magisk: v25100 Stable
LSPosed: 1.8.3 (6552) Zygisk Stable
ClassicPowerMenu: 1.5

App crashes after pressing power button
Try with LSPosed and Accessibility Services
In both cases I got FC
![Screenshot_20220708-082808](https://user-images.githubusercontent.com/1549909/177923315-32215705-49df-4c6f-b869-9d9a15248930.png)

LSPosed log: 
[LSPosed_2022-07-08T08_28_17.386.zip](https://github.com/KieronQuinn/ClassicPowerMenu/files/9069112/LSPosed_2022-07-08T08_28_17.386.zip)

**Comment by KieronQuinn** [comment]
Fixed in 1.5.1
