### ISSUE TITLE
Goes back to lockscreen

### ISSUE THREAD

**Issue by mjain234** [KieronQuinn/ClassicPowerMenu#58]
Hi there
I just suddenly faced this issue and I tried to switch roms but don't know how this happened.
Whenever I open classic power menu, after interacting with any tiles, it takes me back to lockscreen

Android version - Android 12.1

ROM - CrDroid

Device - Realme 2 Pro 
 https://user-images.githubusercontent.com/70900505/179426705-a482d86f-482d-4818-a0f3-9721a1051113.mp4

**Comment by KieronQuinn** [comment]
This isn't being caused by Classic Power Menu, CPM is simply an activity like any other app. The system is doing this.
