### ISSUE TITLE
[Improvement] Standalone launch

### ISSUE THREAD

**Issue by DylanAkp** [KieronQuinn/ClassicPowerMenu#64]
Issue :
As many OEM skins act differently (like OneUI) the system power menu sometimes show over CPM.

Possible fix:
Theses OEM or some third part apps provides a way to remap the power button (or double tap power..etc), in that case, it could be nice to have a Standalone app for the classic power menu so we can remap them to launch this app

**Comment by KieronQuinn** [comment]
This is already integrated, you can launch the power menu directly via an app shortcut. Secondary launch components are buggy and don't play well with all launchers (when disabling/enabling), so the app shortcut will have to do.
