### ISSUE TITLE
Xposed module broken for oxygen is 12

### ISSUE THREAD

**Issue by Liquidbone** [KieronQuinn/ClassicPowerMenu#65]
Ive tried enabling the module in lsposed after a reboot the app stop functioning all together the new menu never opens until I disable the module

**Comment by Liquidbone** [comment]
Device: OnePlus 9
Oxygen os: android 12

**Comment by KieronQuinn** [comment]
OEM customisations are not supported unless a PR is provided to implement them. Use the accessibility option instead.
