### ISSUE TITLE
Add blur

### ISSUE THREAD

**Issue by lollilol** [KieronQuinn/ClassicPowerMenu#66]
On the readme I can see there is blur when you opened the menu, while in reality there isn't. Can you add an option to change the amount of blur?

**Comment by KieronQuinn** [comment]
You probably need to follow

https://github.com/KieronQuinn/ClassicPowerMenu/blob/main/app/src/main/assets/faq.md#background-blur-isnt-working-on-my-device

If not, there's nothing I can do - blur is a system feature and can't be 'fixed' like that.
