### ISSUE TITLE
Reboot Button UI issues

### ISSUE THREAD

**Issue by DrydenD0Texe** [KieronQuinn/ClassicPowerMenu#67]
Reboot fastboot seems to be labbeled as "fastbootd" i think  d is a typo

When rebooting to recovery the rebooting window that opens says "factory reset: restarting"

**Comment by KieronQuinn** [comment]
Not a bug, fastbootd is userspace fastboot: https://source.android.com/docs/core/architecture/bootloader/fastbootd

The app only invokes the system reboot methods for a given type, I do not control what the device does in those modes.
