### ISSUE TITLE
Seems not work on OneUi4. 1

### ISSUE THREAD

**Issue by vstar37** [KieronQuinn/ClassicPowerMenu#68]
I was still got this power panel![Screenshot_20221011-170523_GitHub.jpg](https://user-images.githubusercontent.com/70553922/195047724-434f5035-f1e4-4b3c-b5bb-ebdef47672cf.jpg)

**Comment by KieronQuinn** [comment]
If the accessibility service is not working (even after disabling the Xposed module) then there's nothing I can do. OEM support is community contributed, I do not have a OneUI device to test on.
