### ISSUE TITLE
[Feature Request] Fallback to accessibility api until xposed hooks after reboot

### ISSUE THREAD

**Issue by linux-leo** [KieronQuinn/ClassicPowerMenu#70]
The first time after a reboot when using xposed, the menu doesn't show, so using the accessebility api until it fully hooks would be nice.

**Comment by KieronQuinn** [comment]
This isn't possible since it uses a self hook to know whether hooking is working - there isn't a way to know whether it worked to open the menu. 

Like you said, it only happens once per reboot. Just close and reopen it once, and it will work until the next reboot - it's not a big problem.
