### ISSUE TITLE
Problem Getting Cards

### ISSUE THREAD

**Issue by krisboyy** [KieronQuinn/ClassicPowerMenu#73]
Hope the title and the attached image explains the issue.

![Screenshot_20221108-233741_Classic Power Menu](https://user-images.githubusercontent.com/75375614/200642241-fff9dfd7-d2d8-4941-aece-ae0787aca255.png)

I have two cards synced with GPay. Not running the module, but provided root access from Magisk.

Device: OnePlus Nord running AOSP Android 12
Region: India

**Comment by KieronQuinn** [comment]
This error is coming back from the Wallet API, nothing I can do: https://github.com/KieronQuinn/ClassicPowerMenu/blob/c601751de8aaa146e2d28b2d7779bcb0b451cd16/QuickAccessWallet/src/main/java/com/android/systemui/plugin/globalactions/wallet/WalletPanelViewController.java#L243
