### ISSUE TITLE
Lsposed module not working 

### ISSUE THREAD

**Issue by AlessandroTischer** [KieronQuinn/ClassicPowerMenu#74]
I just changed my rom from A12 to A13. I've had this module working since it's available. Now I see it's working in accessibility mode, but not with lsposed. It simply does not open when I long press power button.

These are my lsposed info:
```
API version
93

Injection Interface
Zygisk

Dex Optimizer Wrapper
Supported

Framework version
1.8.4 (6609)

Manager version
1.8.4 (6609)

System version
13 (API 33)

Device
Xiaomi Mi 9T 

System ABI
arm64-v8a
```

![Screenshot_20221110-102653_LSPosed](https://user-images.githubusercontent.com/23379317/201052441-2cdad8f3-5203-4d07-b5a1-604be5a365c0.png)

I can't see anything useful from logs (but here they are)

[LSPosed_2022-11-10T10_28_27.479147.zip](https://github.com/KieronQuinn/ClassicPowerMenu/files/9979315/LSPosed_2022-11-10T10_28_27.479147.zip)

**Comment by KieronQuinn** [comment]
Are you running MIUI or not? The status bar looks like a custom AOSP-based ROM but you have a MIUI version in your build properties.

**Comment by AlessandroTischer** [comment]
> Are you running MIUI or not? The status bar looks like a custom AOSP-based ROM but you have a MIUI version in your build properties. 

I'm on an AOSP rom (cherish OS 4.2) I think the only thing from xiaomi I still have is the miui cam

**Comment by KieronQuinn** [comment]
I'm guessing that module is setting the MIUI version in the build properties then, there's nothing I can do about that.
