### ISSUE TITLE
[SUGGESTION] Support for MIUI

### ISSUE THREAD

**Issue by UltraStudioLTD** [KieronQuinn/ClassicPowerMenu#77]
> **Note**
This is not **issue** but a **suggestion**.

I see that in most cases **Classic Power Menu** doesn't work on **MIUI** because of trash and broken implementation of **Android** APIs, so I searched for possible fixes and I found one — **Xposed** module called [**CustomMIUIzerMod**](https://github.com/liyafe1997/CustoMIUIzerMod) by @liyafe1997. This module has some methods to allow extended power menu on non-supported devices so I thought that if you integrate/vendor those methods **Classic Power Menu** may also work on **MIUI**!

**Comment by KieronQuinn** [comment]
As I've said many times, I do not have a MIUI device to test on so cannot test changes. MIUI support has been added by the community before, and would need to be again.

**Comment by kilianbalaguer** [comment]
i fixed it with adding does api myself but its shit to do all that so i recomend what i did install custom rom i have pixel os on it and the thing works perfect with xposed
