### ISSUE TITLE
Download button just reboot here

### ISSUE THREAD

**Issue by laltroweb** [KieronQuinn/ClassicPowerMenu#80]
![Screenshot_20221204-121615](https://user-images.githubusercontent.com/16841896/205487418-d0626c4d-44c6-4dec-9c72-8d43487a2fa8.png)

Work so good on pixel 7 pro, but download button (I don't know it's utility) just reboot.

Also  can I add also a setting to disable tile menu if locked?

Ty 😊👍

**Comment by KieronQuinn** [comment]
Download mode is a Samsung feature, it won't work on Pixels. As for disabling when locked, there's an option in the settings to do that.

**Comment by laltroweb** [comment]
Ok, Ty. Removed download.
About remove in lock screen, inmean about quickswitch (or drop-down?) Panel. ATM no way to disable 😅

**Comment by KieronQuinn** [comment]
You mean the wallet? No, that depends on the wallet app as to whether it sends cards while locked.

**Comment by KieronQuinn** [comment]
That is not in scope for an app like this.

**Comment by laltroweb** [comment]
I know. Ok, Ty.
