### ISSUE TITLE
Background blur disabling it's self after a system reboot

### ISSUE THREAD

**Issue by Reiux** [KieronQuinn/ClassicPowerMenu#85]
I did run the command on terminal just what it says:

Opening su
applying the background blur
restarting the system UI (the command one on the FAQ)

And after that It works. But when I restarted my phone, the background blur just keeps disabling it's self after a system reboot.

**Comment by KieronQuinn** [comment]
This is not a CPM bug, you need to run those to enable hardware backed blur in the system. Put them in magisk.d

**Comment by Reiux** [comment]
So am I going to create a sh script file with the commands inside of it then put it on service.d folder in /data/adb?

**Comment by Reiux** [comment]
Just did it and it's now working fine. Thank you.
