### ISSUE TITLE
Build prop lines breaks lsposed module

### ISSUE THREAD

**Issue by AlessandroTischer** [KieronQuinn/ClassicPowerMenu#87]
I'm on an AOSP rom. The module was working fine. When I added these lines (that I need in order to make miui cam scanner work) to the build.prop:

```
ro.miui.ui.version.code=13
ro.miui.ui.version.code=13
ro.miui.ui.version.name=V130
ro.miui.region=CN
```

the module started not to work anymore.

**Comment by KieronQuinn** [comment]
#74 

If you tell the module you're running MIUI and you're not running MIUI, you've done this yourself. It's not feasible for the module to have to detect whether the device is actually running MIUI when you try to trick the system.
