### ISSUE TITLE
Cannot enable accessibility service

### ISSUE THREAD

**Issue by mizzunet** [KieronQuinn/ClassicPowerMenu#92]
![Screenshot_20230406-011713](https://user-images.githubusercontent.com/10193999/230189885-09e4e32f-271b-4cc9-bbe9-10af204f7567.png)

Device is Pixel 4a running CalyxOS Android 14

**Comment by KieronQuinn** [comment]
You have to reinstall the app (uninstall it completely first) using Split APKs Installer or the APKMirror app. This is a new restriction on sideloaded apps in Android 14, and not a bug.

**Comment by KieronQuinn** [comment]
Nope, not possible
