### ISSUE TITLE
Classic Power Menu 1.6 crashing on Android 14 Beta 1

### ISSUE THREAD

**Issue by abun880007** [KieronQuinn/ClassicPowerMenu#94]
Classic Power Menu crashes on Android 14 When doing a power button long press.  I have attached a logcat to see if it helps you locate the issue.

[Classic_Power_Menu_1.6_A14_logcat.txt]
(https://github.com/KieronQuinn/ClassicPowerMenu/files/11242487/Classic_Power_Menu_1.6_A14_logcat.txt)

**Comment by KieronQuinn** [comment]
Fixed in 1.6.1

**Comment by abun880007** [comment]
thanks for the quick fix all working fine now

Kind Regards,



Adam Bunting
________________________________
