### ISSUE TITLE
Cannot add new card

### ISSUE THREAD

**Issue by DrKoneko** [KieronQuinn/ClassicPowerMenu#96]
I created a new card using Pass2Pay and added it to my Google wallet. it shows up on Google pay but not classic power menu. The only card that shows up in classic power menu is my Lego VIP card, and I can't manually add cards

**Comment by KieronQuinn** [comment]
Can you please make a fake card (no personal info) in pass2pay of the same type and share the link, then I can see if I can reproduce

**Comment by DrKoneko** [comment]
Well, I'm not sure how to do that because you have to make a card in the app, and then add it to your wallet. But I fixed the issue I was having. Basically what I was trying to do was create a card with a qr code on it to get into my gated community and then add it to CPM so that I could access the card quickly. However it wasn't showing the card when I added it. I fixed this by changing to a loyalty rewards card at which point it will show up in the power menu. Just in case anyone else has this specific problem.

**Comment by KieronQuinn** [comment]
Yes, that is why it says loyalty cards - it only supports loyalty cards.
