### ISSUE TITLE
Not working with Samsung A13 latest firmware

### ISSUE THREAD

**Issue by Shidapu** [KieronQuinn/ClassicPowerMenu#98]
I'm using Samsung stock firmware A13, April security patches with Galaxy Fold3, and Classic power Menu doesnt work at all for me, with root, LSPosed and accessibility service. Side button setting is set to show power menu and no Bixby stuff.

I get no errors from scoop.

**Comment by KieronQuinn** [comment]
Try disabling the LSPosed module and rebooting

**Comment by Shidapu** [comment]
> Try disabling the LSPosed module and rebooting

Disabling LSPosed seems to work. With delays when long pressing.

![Uploading Screenshot_20230505_173206_Shell.jpg…]()
![Uploading Screenshot_20230505_173231_Shell.jpg…]()

**Comment by Shidapu** [comment]
> That is normal. OneUI is not guaranteed to work with Xposed.

Xposed is working great on OneUi though. But not the module CPM.

Thanks for assisting! Such a great app! Been looking for something like this for a long time.

**Comment by KieronQuinn** [comment]
> > That is normal. OneUI is not guaranteed to work with Xposed.
> 
> Xposed is working great on OneUi though. But not the module CPM.
> 
> Thanks for assisting! Such a great app! Been looking for something like this for a long time.

No, the module is not guaranteed to work. It relies on community support, much like MIUI.
